Repository quotient-im/Quaternion, pull requests merged in 2019-02, with the labels that each got.

#479 Fixed incorrect file name mention in README.md.
  README.md
Labels: documentation

#485 MainWindow: add close button to the About dialog
  client/mainwindow.cpp
Labels: enhancement

#489 ImageContent: align image to the left
  client/qml/ImageContent.qml
Labels: enhancement

#495 Fix hide mainwindow
  client/activitydetector.cpp
  client/main.cpp
Labels: bug

#484 add support for qtkeychain to store access tokens
  .travis.yml
  BUILDING.md
  CMakeLists.txt
  client/mainwindow.cpp
  client/mainwindow.h
Labels: enhancement

#505 Add login warning dialog for logging into the same account
  client/dialog.cpp
  client/mainwindow.cpp
Labels: enhancement
