Repository quotient-im/Quaternion, pull requests merged in 2021-01, with the labels that each got.

#724 Fix tr call missing
  client/models/messageeventmodel.cpp
Labels: bug

#725 Timeline tweaks
  CMakeLists.txt
  client/chatroomwidget.cpp
  client/chatroomwidget.h
  client/main.cpp
  client/qml/ActiveLabel.qml
  client/qml/TextElider.qml
  client/qml/Timeline.qml
  client/qml/TimelineItem.qml
  client/quaternionroom.cpp
  client/quaternionroom.h
  client/resources.qrc
Labels: enhancement

#727 New read marker
  client/chatroomwidget.cpp
  client/models/messageeventmodel.cpp
  client/models/messageeventmodel.h
  client/qml/Timeline.qml
  client/qml/TimelineItem.qml
Labels: enhancement

#728 Update brew installation command
  README.md
Labels: documentation

#729 scroll to reader marker
  client/qml/ScrollToButton.qml
  client/qml/Timeline.qml
  client/resources.qrc
  icons/scrollup.svg
Labels: enhancement
